### ISSUE TITLE
OAuth fails

### ISSUE THREAD

**Issue by jhiemer** [ImmobilienScout24/restapi-java-sdk#3]
Hi, 
according to the documentation here: http://api.immobilienscout24.de/useful/tutorials-sdks-plugins/tutorial-java-signpost.html

``` java
OAuthConsumer consumer = new DefaultOAuthConsumer(consumerKey, secrectKey); 

        OAuthProvider provider = new DefaultOAuthProvider("http://sandbox.immobilienscout24.de/restapi/security/oauth/request_token", 
                "http://sandbox.immobilienscout24.de/restapi/security/oauth/access_token", 
                "http://sandbox.immobilienscout24.de/restapi/security/oauth/confirm_access");

        log.info("Fetching request token...");

        String authUrl = provider.retrieveRequestToken(consumer, "http://www.google.de");

```

this should work for signing in via OAuth. But what I always get is:

``` trace
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: http://sandbox.immobilienscout24.de/restapi/security/oauth/request_token
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:214)
    at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:69)
    at de.project.immoscout.Immoscout24OAuth.authenticate(Immoscout24OAuth.java:38)
    at de.project.immoscout.Immoscout24OAuthTest.test(Immoscout24OAuthTest.java:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.FileNotFoundException: http://sandbox.immobilienscout24.de/restapi/security/oauth/request_token
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
    at oauth.signpost.basic.HttpURLConnectionResponseAdapter.getContent(HttpURLConnectionResponseAdapter.java:18)
    at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:228)
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:189)
    ... 26 more
Caused by: java.io.FileNotFoundException: http://sandbox.immobilienscout24.de/restapi/security/oauth/request_token
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
    at oauth.signpost.basic.HttpURLConnectionResponseAdapter.getStatusCode(HttpURLConnectionResponseAdapter.java:22)
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:178)
    ... 26 more
```

Anything I am doing wrong? 

Btw: This could be in the documentation here referenced as well.

**Comment by jhiemer** [comment]
The URL:  http://rest.immobilienscout24.de/restapi/security/oauth/access_token (401, with Sandbox credentials) actually works and brings up, what I expected, while neither  http://rest.sandbox.immobilienscout24.de/restapi/security/oauth/access_token (no mapping at all) nor  http://sandbox.immobilienscout24.de/restapi/security/oauth/access_token (404) are working.

**Comment by jhiemer** [comment]
Okay, when looking into other samples one can see that it is: _.sandbox-immobilienscout24.de._

Would be really helpful to revise the documentation.
