### ISSUE TITLE
OAuth authentication with stored credentials

### ISSUE THREAD

**Issue by jhiemer** [ImmobilienScout24/restapi-java-sdk#4]
Hi,
I followed the Tutorial http://api.immobilienscout24.de/useful/tutorials-sdks-plugins/tutorial-java-signpost.html, which described how to authorise for communication with the immoscout API. The initial connection works. Afterwards I tried to reauthenticate with stored credentials like this:

``` txt
07:53:55.748 [main] INFO  d.project.immoscout.Immoscout24OAuth - Enter the verification code and hit ENTER when you're done:
T8dxpr
07:54:04.459 [main] INFO  d.project.immoscout.Immoscout24OAuth - Fetching access token...
07:54:17.134 [main] INFO  d.project.immoscout.Immoscout24OAuth - Access token: 004bcd0d-5d4c-46dc-9c47-b11eb54d6e18
07:54:18.823 [main] INFO  d.project.immoscout.Immoscout24OAuth - Token secret: bIKKofo+L6W8gwjfNvFlwCb3OcW5sx/FhaRpQsExAV48xQgeb8fuqnI3YXaJKDOkAVXSnHWIY33RDtp6osgpvGpusn4sj326/Zqtwadi2i4=
```

The credentials above and the verification code got stored in a database, and afterwards used as below:

``` java
OAuthConsumer consumer = new DefaultOAuthConsumer(consumerKey, consumerKey);

        consumer.setTokenWithSecret("004bcd0d-5d4c-46dc-9c47-b11eb54d6e18", 
                "bIKKofo+L6W8gwjfNvFlwCb3OcW5sx/FhaRpQsExAV48xQgeb8fuqnI3YXaJKDOkAVXSnHWIY33RDtp6osgpvGpusn4sj326/Zqtwadi2i4=");

        OAuthProvider provider = new DefaultOAuthProvider("http://rest.sandbox-immobilienscout24.de/restapi/security/oauth/request_token", 
                "http://rest.sandbox-immobilienscout24.de/restapi/security/oauth/access_token", 
                "http://rest.sandbox-immobilienscout24.de/restapi/security/oauth/confirm_access");


        provider.setOAuth10a(true);

        provider.retrieveAccessToken(consumer, "T8dxpr");

        log.info("Access token: " + consumer.getToken());

        log.info("Token secret: " + consumer.getTokenSecret());

        OAuthToken oAuthToken = new OAuthToken(consumer.getToken(), consumer.getTokenSecret());

        return oAuthToken;
```

The result is sadly a Bad Request with a 400.

``` trace
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Server returned HTTP response code: 400 for URL: http://rest.sandbox-immobilienscout24.de/restapi/security/oauth/access_token
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:214)
    at oauth.signpost.AbstractOAuthProvider.retrieveAccessToken(AbstractOAuthProvider.java:97)
    at de.project.immoscout.Immoscout24OAuth.authenticate(Immoscout24OAuth.java:84)
    at de.project.immoscout.Immoscout24OAuthTest.test(Immoscout24OAuthTest.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://rest.sandbox-immobilienscout24.de/restapi/security/oauth/access_token
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
    at oauth.signpost.basic.HttpURLConnectionResponseAdapter.getContent(HttpURLConnectionResponseAdapter.java:18)
    at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:228)
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:189)
    ... 26 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://rest.sandbox-immobilienscout24.de/restapi/security/oauth/access_token
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
    at oauth.signpost.basic.HttpURLConnectionResponseAdapter.getStatusCode(HttpURLConnectionResponseAdapter.java:22)
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:178)
    ... 26 more
```

Is there anything I am doing wrong?

Btw. The documentation for OAuth, including links (e.g. registration) and URLs/Code Snippet could be revised.

**Comment by killaqueen** [comment]
Johannes,

I am not shure why you are trying to retrieve the access token twice. But guess your old token will be overwritten. If you already got the access token and secret the you can use

<code>
api.init("myConsumerKey", "myConsumerSecret", "http://rest.sandbox-immobilienscout24.de/restapi/api");
</code>
<code>
api.signIn("UserAccesstoken", "UserAccesssecret");
<code>

Have a look here:

https://github.com/ImmobilienScout24/restapi-java-sdk/wiki/Getting-started

Cheers,

Martin

**Comment by jhiemer** [comment]
@killaqueen 
great, yep that works. Documentation should really be updated though. It is not quite straightforward to gather the right information for a successful usage of the api at all.

Thanks anyway.

**Comment by killaqueen** [comment]
Yes, the "Oauth getting startet" ist rather old. We will update it. But after you got your access token you can refer to the gitHub wiki. This should all you need to handle the sdk.

Cheers,

Martin
