### ISSUE TITLE
Internal Server Error when posting Realestate

### ISSUE THREAD

**Issue by jhiemer** [ImmobilienScout24/restapi-java-sdk#6]
Hi,
I have some integration tests running which are failing since this week with: 

``` batch
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://rest.sandbox-immobilienscout24.de/offer/v1.0/user/me/realestate/?usenewenergysourceenev2014values=true
```

The message is not very descriptive. Any idea what is happening here?

Tested with 0.2.9 & 0.2.11

**Comment by jhiemer** [comment]
Seems to be a more general issue with the sandbox, getting the same error, when trying to create a contact.

**Comment by killaqueen** [comment]
HI,

thanks for the info. We will check this.Can you please provide a mor detailed stacktrace?

Thanks.

Cheers,

Martin

**Comment by jhiemer** [comment]
Hi Martin,
here you go:

``` bash
java.lang.RuntimeException: null: 
    at de.is24.rest.api.export.api.parser.impl.AbstractResultParser.throwException(AbstractResultParser.java:73)
    at de.is24.rest.api.export.api.parser.impl.CreateRealestateResultParser.throwException(CreateRealestateResultParser.java:62)
    at de.is24.rest.api.export.api.parser.impl.AbstractResultParser.handleException(AbstractResultParser.java:48)
    at de.is24.rest.api.export.api.impl.IS24ApiImpl.sendBodyRequest(IS24ApiImpl.java:768)
    at de.is24.rest.api.export.api.impl.IS24ApiImpl.sendPostRequest(IS24ApiImpl.java:723)
    at de.is24.rest.api.export.api.impl.IS24ApiImpl.createRealestate(IS24ApiImpl.java:141)
    at de.is24.rest.api.export.api.impl.IS24ApiImpl.createRealestate(IS24ApiImpl.java:146)
    at de.sample.cloud.immoscout.Immoscout24.createRealEstate(Immoscout24.java:72)
    at de.sample.cloud.immoscout.Immoscout24Test.testShouldExportWithCertificateAfter2014(Immoscout24Test.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://rest.sandbox-immobilienscout24.de/offer/v1.0/user/me/realestate/?usenewenergysourceenev2014values=true
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1838)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
    at de.is24.rest.api.export.api.impl.IS24ApiImpl.sendBodyRequest(IS24ApiImpl.java:757)
    ... 35 more

```

**Comment by killaqueen** [comment]
Hi Johannes,

i cannot reproduce the issue. Nor with 0.2.7 nor with 0.2.11. Does it still occur on your site?

**Comment by jhiemer** [comment]
Hi Martin,
yes still occurring here. Maybe I have found the origin: 

In the URL there is /api missing: http://rest.sandbox-immobilienscout24.de/offer/v1.0/user/me/realestate/?usenewenergysourceenev2014values=true could that be the origin?

**Comment by jhiemer** [comment]
My bad, should work on weekends. That was the problem.

Thanks Martin!

**Comment by killaqueen** [comment]
You are welcome :)
